# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\LineScanOCT\LineScanOCT-master\SampleLocatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(885, 748)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pic_window = QtWidgets.QLabel(self.layoutWidget)
        self.pic_window.setMinimumSize(QtCore.QSize(717, 0))
        self.pic_window.setAutoFillBackground(True)
        self.pic_window.setScaledContents(True)
        self.pic_window.setObjectName("pic_window")
        self.horizontalLayout.addWidget(self.pic_window)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.finishwell = QtWidgets.QPushButton(self.layoutWidget)
        self.finishwell.setMinimumSize(QtCore.QSize(0, 100))
        icon = QtGui.QIcon.fromTheme("200")
        self.finishwell.setIcon(icon)
        self.finishwell.setObjectName("finishwell")
        self.verticalLayout.addWidget(self.finishwell)
        self.finishplate = QtWidgets.QPushButton(self.layoutWidget)
        self.finishplate.setMinimumSize(QtCore.QSize(0, 100))
        self.finishplate.setObjectName("finishplate")
        self.verticalLayout.addWidget(self.finishplate)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pic_window.setText(_translate("Form", "TextLabel"))
        self.label.setText(_translate("Form", "click left to draw"))
        self.label_2.setText(_translate("Form", "click right to back"))
        self.finishwell.setText(_translate("Form", "finish this well"))
        self.finishplate.setText(_translate("Form", "finish the whole plate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
